### ISSUE TITLE
Error building  eval-win10x64-enterprise

### ISSUE THREAD

**Issue by eoyslebo** [boxcutter/windows#119]
Build times out around when update.bat runs.

If I remove update.bat from eval-win10x64-enterprise.json, the build completes without issues.

If you manually log in as vagrant user with password vagrant, the build continues and updates work.

**Comment by ddavidebor** [comment]
same here on parallels.

**Comment by ddavidebor** [comment]
I'm rebuilding all eval boxes on parallels, saving all the logs, so we might get a decent insight on what is happening.

**Comment by ddavidebor** [comment]
Here it is! 120 errors
[nohup.txt](https://github.com/boxcutter/windows/files/1286391/nohup.txt)

**Comment by elatt** [comment]
I believe the issue is a bug in the Win10 build we are using. 
```Addressed issue where, if you specify an auto-logon configuration in Unattend.xml, auto-logon only works on the first logon, but will not work again when the device is restarted.```
https://support.microsoft.com/en-in/help/4022716/windows-10-update-kb4022716

If there is new install media availiable with this fix included then that would be great. Otherwise I think we may need a script which (re-)enables auto-logon before `update.bat` runs:
https://support.microsoft.com/en-us/help/324737/how-to-turn-on-automatic-logon-in-windows
