### ISSUE TITLE
Puppet msi installer fails because url has changed

### ISSUE THREAD

**Issue by gavioto** [boxcutter/windows#187]
The package location has changed, and 'latest' version doesn't work. 

![image](https://user-images.githubusercontent.com/2454642/66555013-4179f980-eb4e-11e9-8ab7-a1ffd93aaacf.png)

WORKAROUND: use specific version like 'x86-latest' in Makefile.local should work. But take into account that some O.S. may not support 32 bits applications.

**Comment by arizvisa** [comment]
This seems related to PR #178. Before I test+merge it though, I'm waiting for a response from that maintainer since it's been a while.

After merging one other PR to allow better relocation of the templates and using them outside our build system, the provisioners are next on my list.

Thanks for your patience!

**Comment by arizvisa** [comment]
PR #206 was merged which should fix this issue. It also still keeps support for the older Puppet versions if you want those for some reason.

I tested each case on the `eval-win7x86-enterprise.json`, `eval-win7x64-enterprise.json`, `eval-win81x86-enterprise.json`, and the `eval-win81x64-enterprise.json` templates. Other than the potential issues that those templates may have, puppet should still install.

Closing this issue due to the PR being merged. Let me know if it still has problems installing puppet for some reason, and I'll re-open this.
