### ISSUE TITLE
Packer doesn't complete the rest of the batches in floppy_files after update

### ISSUE THREAD

**Issue by jonyeezs** [boxcutter/windows#19]
Creating a Hyper-v box.
Using your update batch from pbolduc/windows-vm/script/update.bat

i've included it into my floppy_files to run.

00-run-all-scripts.cmd is there and zzz-shutdown.bat.

It completes the update.bat successfully, restarts server and configs the updates.
Then it just does nothing at all. Does not run the rest of the scripts.
I manually ran 00-run-all-scripts.cmd again and it then shutsdown to run the provisioners.

I understand that your update.bat is in the script folder. But i've seen it being used in cases at unattended.

Would that be the issue? Or am i missing steps?

Note: I'm just running packer build *.json instead of using the makefile you have.

**Comment by rasa** [comment]
Try renaming `zzz-shutdown.bat` to `zzzz-shutdown.bat` and see if that fixes it. packer has issues with files of 13 characters long. See https://github.com/mitchellh/go-fs/pull/2

**Comment by dhekimian** [comment]
With the new WinRM provisioner, when updates.bat reboots the VM to process the updates Windows starts WinRM "automatically" on the way up. 

To fix it I disabled the service in `install-winrm.cmd` and enable it in `zz-start-sshd.cmd`. I also added `regenerate-dotnet-cache.cmd` to come after `updates.bat` but before `zz-start-sshd.cmd` because if you put it in the scripts session, during execution it will kill the WinRM session stopping the Packer build.

## `install-winrm.cmd`

### From:
```batch
echo ==^> Stopping winrm service
sc stop winrm
```

### To:
```batch
echo ==^> Stopping winrm service
sc stop winrm
sc config winrm start= disabled
```

## `zz-start-sshd.cmd`

### From
```batch
    echo ==^> Starting the %%i service
    sc start %%i
```
### To:
```batch
    echo ==^> Starting the %%i service
    sc start %%i
    sc config %%i start= auto
```

*Ensure you put the space after `start=` or it wont work.*
