### ISSUE TITLE
Maintenance help?

### ISSUE THREAD

**Issue by arizvisa** [boxcutter/windows#190]
Is this still being maintained? There hasn't been any commits since my last PR from February, and there's some issues that are left unanswered. I use this repo as a base for a project of mine so I don't mind helping pick up the slack if that's the case.

**Comment by annawake** [comment]
I’ll invite you to the maintainers tomorrow sometime if you’d like to contribute.

I’ve been using the https://github.com/boxcutter/windows-ps <https://github.com/boxcutter/windows-ps> templates and mostly docker for windows, rather than these, so I don’t even have a setup to easily verify changes in these repos anymore. If you’d like to keep these scripts updated and verify changes, that would be great.

**Comment by arizvisa** [comment]
Yeah, definitely. I'm in infosec and so having access to a number of these versions for both architectures (and even the older versions that were culled) has been of significant for tracking the historical changes of the different binaries. I've been maintaining a local version that's de-vagrantified, but for sure there's a number of people that are still interested in these.

But regardless about my de-vagrantified fork, I'll be happy to do anything to move these PRs along and fix some of the templates like win7x86-enterprise, and win2008r2-standard.

**Comment by arizvisa** [comment]
Thx annawake, I'll start working through some of these PRs as I know how much it sucks to watch a codebase change while waiting for your PR to even get looked at, and then I'll start working more on some of these issues and broken templates.
