### ISSUE TITLE
Instructions for Windows Environment

### ISSUE THREAD

**Issue by leo4all** [boxcutter/windows#36]
Can anyone suggest how to build / run this from windows environment
how to run the make command and tied with packer path etc.

**Comment by jriffel** [comment]
I would like to know the same thing...

**Comment by rasa** [comment]
I use Cygwin.

**Comment by vmenajr** [comment]
I did a "make -n vmware/win7x64-enterprise" from a *nix vm just to see the packer execution command then ran that.  Seems to have worked.  I use mobaxterm on windows.

**Comment by donbecker** [comment]
I'm also using Cygwin on Windows 7 to build the boxes.

**Comment by smudgerdan** [comment]
Wondering if creating a psake version of the makefile is worth while?

**Comment by rhealitycheck** [comment]
@smudgerdan I would say it's worthwhile. I'm also running into this issue and am checking out @vmenajr's solution of using mobaxterm to see if that will work for me.

**Comment by JoelBCarter** [comment]
I'm currently playing around with trying to add support for Packer's Hyper-V ISO Builder to some of these templates.  That would be a nice way to have this feature addressed for Windows builds.

**Comment by arizvisa** [comment]
Personally if I need to use GNU Make on Windows, I use msys2. However, you can now use the templates directly with Packer by passing your desired template to `packer build`.

If you prefer, I can add documentation on how to use the templates directly like I mentioned w/o the need for any posix environment. Let me know if so.

Otherwise, this issue seems to have gone stale. Unless someone objects, I'll close this in one month.

**Comment by arizvisa** [comment]
Closing this. Let me know if closing it is a mistake and I'll re-open it. Thanks.
