### ISSUE TITLE
Remove cygwin and openssh builds?

### ISSUE THREAD

**Issue by rasa** [boxcutter/windows#72]
With winrm, we don't need these builds any more, and they just overly complexify things. Also, if a user needs them, we can modify [bin/tweak-json.py](../blob/master/bin/tweak-json.py) to regenerate them.

Therefore, I volunteer to remove them. @annawake?

**Comment by jebegin** [comment]
I was unable to make vmware//win7x86-enterprise today.  I kept getting an error when the VMware tools were suppose to upload, right after WinRM successfully connected.  I tried make clean before trying again and it failed the same way.  I then tried make vmware//win7x86-enterprise-ssh and it worked.  So removing ssh and cygwin would be removing a quick work around when WinRM is obviously not working right.

**Comment by rasa** [comment]
I fixed that issue locally, using
`winrm set winrm/config/winrs @{MaxMemoryPerShellMB="2048"}`

**Comment by jebegin** [comment]
rasa, I'm new to using packer/boxcutter/vagrant/chocolately.  I'm currently on a Windows 10 PC using VMware Workstation and I'm not aware of where I would use that winrm set command?  Is it something I configure for my Windows environment or for VMware somehow?  Does it go into a config file?  Thanks.

**Comment by jebegin** [comment]
rasa, never mind, I figured it out.

**Comment by Azulinho** [comment]
openssh/cygwin builds are pretty useful, for example I use packer/vagrant for running windows builds on remote bare-metal boxes which only have remote access over ssh. 

Being able to do ssh into one of those remote vbox builds is priceless.
(ssh -X/vnc/rdp is not an option)

**Comment by casept** [comment]
This would make the boxes unusable on linux and OSX as these platforms don't have winrm client support in vagrant.

**Comment by dragon788** [comment]
Linux and OSX had the `vagrant-winrm` plugin available and I believe in more recent versions the functionality has been rolled into Vagrant proper, so it shouldn't even require a plugin anymore.

**Comment by arizvisa** [comment]
I'm all for this removal as well.

**Comment by arizvisa** [comment]
It appears that the vote is to not remove these templates.

How about consolidating them? There aren't too many differences between the templates, it might be possible to use something like `jq` to merge the ssh or cygwin parts into the main template?

If there's no interest in either of the aforementioned solutions, I'll likely close this in a month or so as "wontfix" if nobody has any objections. Let me know.

**Comment by dragon788** [comment]
Now that Packer supports writing templates in HCL I wonder if there is an option to write them in HCL and do an import or merge on top of a base with the SSH and cygwin functionality and export to JSON. I'd definitely hope to avoid going too crazy with having code that generates templates just to avoid a little bit of repeated code.

**Comment by arizvisa** [comment]
Yeah, agreed on avoiding going crazy with generating templates for everything.

With regards to `jq` or whatever other mechanism, I was thinking something along the lines of the following...like you can do relatively quick merges like the following to add/replace some fields to an individual builder.
```
jq '.builders[] |= . + {"communicator":"ssh","ssh_username":"blah","ssh_password":"blah"}' eval-win7x86-enterprise.json
```
This logic simply adds the communicator, ssh_username, and ssh_password from specified dict into each of the builder elements for a template.

But with regards to integrating this into boxcutter/windows, it'd probably look something more like the following if we've isolated the ssh-specific/cygwin-specific components into their own json. I've been doing this sort of stuff in my own fork of boxcutter/windows to de-vagrantify all of the templates, and to change the default usernames/passwords.
```
jq --slurpfile builders /path/to/ssh-builders.json --slurpfile provisioners /path/to/ssh-provisioners.json '(.provisioners[].scripts += $provisioners) | (.builders[] |= . + $ssh)' eval-win7x86-enterprise.json
```

But, to avoid forcing people to have to build these templates themselves (which'd require having jq), we could split up the logic for ssh-ifying (or cygwin-ifying) a template into the makefile, and then have a maintainer just ensure that its part of a pre-commit hook or something similar so that from the users' perspective, nothing appears to have changed.

Re-writing all of the json templates in HCL kind of feels out of scope for this project, especially since its kind-of in "maintenance" mode. It might be better to consider a whole rewrite for non-json templates in some newer project like `github.com/boxcutter/windows-ps` or something similar

**Comment by arizvisa** [comment]
This issue has had no discussion or input for over 6 months. I've tagged it as stale and as a result this issue will be closed in 1 month.

If you disagree and feel this decision is a mistake, please let me know and I'll remove the label.

**Comment by arizvisa** [comment]
Closing this issue as it's been stale for over a month.
