### ISSUE TITLE
Virtualbox oracle-cert expired

### ISSUE THREAD

**Issue by NoumanSaleem** [boxcutter/windows#90]
The oracle-cert included with this repo is expired, causing the installation of virtualbox guest-additions to fail.

**Comment by bflad** [comment]
In my local setup I was able to overwrite `floppy/oracle-cert.cer` with `cert/vbox-sha1.cer` from the VirtualBox 5.1.14 Guest Additions ISO (found at `/Applications/VirtualBox.app/Contents/MacOS/VBoxGuestAdditions.iso` on OS X) and have the Guest Additions install correctly running `make virtualbox/eval-win7x64-enterprise`. I'm not sure if that's the correct way to handle this situation (we might want to use the built-in ISO `cert/VBoxCertUtil.exe` available since VirtualBox 4.2), but thought I'd share.

**Comment by tas50** [comment]
Resolved in https://github.com/boxcutter/windows/pull/100 until 2019 although I think https://github.com/exospheredata/boxcutter_windows/commit/7346b6ab84aa61acf74a0081377845943ee756bc is probably a better long term solution

**Comment by tas50** [comment]
I've fixed this on master until sometime in 2019, which gives us some time to better pull the cert right from the ISO
